### ISSUE TITLE
build.sh issue on message proto files not ending with _message_proto

### ISSUE THREAD

**Issue by gucluoz** [appnexus/pyrobuf#4]
Since setup.py only cythonizes pyx files ending with '**_message_proto**', one can not use build.sh with them.

**Comment by tburmeister** [comment]
Can you clarify what the issue is here? `setup.py` cythonizes the `.pyx` files ending with `_message_proto` in the `/out` folder, but cythonizes all `.pyx` files in the `/src` folder; this is intentional -- it separates the Cython code generated from `.proto` specs from the shared "utility" code in `/src`.
