### ISSUE TITLE
tokenize() parse exception on spacing

### ISSUE THREAD

**Issue by AndreMiras** [appnexus/pyrobuf#63]
I don't know if it's a bug or a feature since I don't know very much about the protobuf spec.
I'm currently playing with a proto file ([vector_tile.proto](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto)) which raised few issues.
One of the issues is related with spacing around `packed = true` like so: `[ packed = true ]`.
It leads to a `Exception: Unexpected character 'r' in line 5: 'ields` message.

**Comment by tburmeister** [comment]
This is a minor bug, I'll have a PR up soon.

**Comment by AndreMiras** [comment]
That was a fast reply, thank you!

**Comment by tburmeister** [comment]
Hey @AndreMiras,

I have a [PR](https://github.com/appnexus/pyrobuf/pull/64) that fixes the parse error, as well as a subsequent parse error, but discovered two more issues with this proto spec:

1. We don't currently support [extensions](https://developers.google.com/protocol-buffers/docs/proto#extensions) , though with my changes we can at least parse specs that have them.

2. Even though with the changes we can parse this spec, the generated code will not compile because of Issue #55, which I am now realizing is a pretty big one.

I'll try to devote some time to issue #55 when I have some spare time, but unfortunately it means getting your spec to compile is not quite as quick a fix as I had hoped.

**Comment by AndreMiras** [comment]
Hi @tburmeister, thank you so much for such a quick feedback!
Yes I'm aware of the two other issues. Even though I'm totally new to protobuf, I may find time to learn about more about it and take a look at #55.

**Comment by AndreMiras** [comment]
Since #64 was merged and I could test it successfully on master, I'm closing this issue, thank you.
```
$ pyrobuf vector_tile.proto --install
generating vector_tile.proto
Compiling out/vector_tile_proto.pyx because it changed.
[1/1] Cythonizing out/vector_tile_proto.pyx
running build
running build_ext
building 'vector_tile_proto' extension
creating build
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/out
x86_64-pc-linux-gnu-gcc -pthread -fPIC -I/usr/include/python2.7 -c out/vector_tile_proto.c -o build/temp.linux-x86_64-2.7/out/vector_tile_proto.o
creating build/lib.linux-x86_64-2.7
x86_64-pc-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,--as-needed -L. build/temp.linux-x86_64-2.7/out/vector_tile_proto.o -L/usr/lib64 -lpython2.7 -o build/lib.linux-x86_64-2.7/vector_tile_proto.so
running install
running install_lib
copying build/lib.linux-x86_64-2.7/vector_tile_proto.so -> /tmp/trash/pyrobuftest/venv/lib64/python2.7/site-packages
running install_egg_info
Writing /tmp/trash/pyrobuftest/venv/lib64/python2.7/site-packages/vector_tile-0.0.0-py2.7.egg-info
$ python -c "from vector_tile_proto import Tile"
```
